version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - 4321:4321

  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    ports:
      - 3000:3000
