# apps/api/Dockerfile.dev
FROM node:16

WORKDIR /usr/src/api

# Copia los archivos de configuración de paquetes
COPY ./apps/api/package.json ./package.json
COPY ./apps/api/package-lock.json ./package-lock.json

# Instala las dependencias
RUN npm install --registry=https://registry.npm.taobao.org
RUN npm config set fetch-retry-maxtimeout 600000

# Copia el código fuente de la API
COPY ./apps/api .

# Comando para ejecutar la API en modo desarrollo
CMD ["npm", "run", "dev"]
